### ISSUE TITLE
Compile failed 

### ISSUE THREAD

**Issue by JsHuang** [volca/wireless_usb_disk#3]
Follow readme to compile this project appears error as below:

```
D:\wireless_usb_disk-main>..\arduino-cli\bin\arduino-cli.exe compile .
打开项目时出错：项目中缺少主文件：D:\wireless_usb_disk-main\wireless_usb_disk-main.ino
```

**Comment by volca** [comment]
Please rename the folder `wireless_usb_disk-main` to `wireless_usb_disk` instead

**Comment by JsHuang** [comment]
Thanks. By the way ,the fqbn aslo must be set to make a successful make. Like
`arduino-cli.exe compile -b esp32:esp32:esp32s2 .`

**Comment by volca** [comment]
Yes. We can pre-configure the fqbn in [sketch.json](https://github.com/volca/wireless_usb_disk/blob/main/sketch.json#L3)

**Comment by JsHuang** [comment]
> Yes. We can pre-configure the fqbn in [sketch.json](https://github.com/volca/wireless_usb_disk/blob/main/sketch.json#L3)

Using `arduino-cli.exe compile .` didn't automatically found this pre-configuration.

Another question, according to ESP32 documentation, using USB to update the firmware need to build a DFU type image. Did this project also compile a DFU image?
Thanks.

**Comment by volca** [comment]
> Did this project also compile a DFU image?

No. It doesn't. You need do it yourself.
